In [4]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../Data/Raw")

df_home = pd.read_csv(DATA_DIR / "Home Credit Default Risk Dataset" / "application_train.csv")
df_lending = pd.read_csv(DATA_DIR / "Lending Club Loan Dataset" / "loans_full_schema.csv")

for name, df in [("Home Credit", df_home), ("LendingClub", df_lending)]:
    print(f"{name}: {df.shape[0]} rows, {df.shape[1]} columns")

Home Credit: 307511 rows, 122 columns
LendingClub: 10000 rows, 56 columns

In [19]:
from ucimlrepo import fetch_ucirepo

statlog_german_credit_data = fetch_ucirepo(id=144)
X = statlog_german_credit_data.data.features
y = statlog_german_credit_data.data.targets

df_german = X.copy()
df_german["target"] = y

column_names = [
    "status_checking_account", "duration_months", "credit_history", "purpose",
    "credit_amount", "savings_account", "employment_since", "installment_rate_pct",
    "personal_status_sex", "other_debtors_guarantors", "residence_since",
    "property", "age", "other_installment_plans", "housing",
    "existing_credits_count", "job", "num_dependents", "telephone",
    "foreign_worker"
]
df_german.columns = column_names + ["target"]

In [17]:
print(df_german["status_checking_account"].unique())
print(df_german["credit_history"].unique())
print(repr(df_german["status_checking_account"].iloc[0]))

<StringArray>
['A11', 'A12', 'A14', 'A13']
Length: 4, dtype: str
<StringArray>
['A34', 'A32', 'A33', 'A30', 'A31']
Length: 5, dtype: str
'A11'

In [7]:
column_names = [
    "status_checking_account", "duration_months", "credit_history", "purpose",
    "credit_amount", "savings_account", "employment_since", "installment_rate_pct",
    "personal_status_sex", "other_debtors_guarantors", "residence_since",
    "property", "age", "other_installment_plans", "housing",
    "existing_credits_count", "job", "num_dependents", "telephone",
    "foreign_worker"
]

df_german.columns = column_names + ["target"]
print(df_german.columns.tolist())
df_german.head()

['status_checking_account', 'duration_months', 'credit_history', 'purpose', 'credit_amount', 'savings_account', 'employment_since', 'installment_rate_pct', 'personal_status_sex', 'other_debtors_guarantors', 'residence_since', 'property', 'age', 'other_installment_plans', 'housing', 'existing_credits_count', 'job', 'num_dependents', 'telephone', 'foreign_worker', 'target']

,status_checking_account,duration_months,credit_history,purpose,credit_amount,savings_account,employment_since,installment_rate_pct,personal_status_sex,other_debtors_guarantors,...,property,age,other_installment_plans,housing,existing_credits_count,job,num_dependents,telephone,foreign_worker,target
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [9]:
df_german.to_csv(GERMAN_DIR / "german_credit_uci_original.csv", index=False)

In [20]:
status_checking_account_map = {
    "A11": "< 0 DM", "A12": "0 <= ... < 200 DM",
    "A13": ">= 200 DM / salary assignment", "A14": "no checking account"
}
credit_history_map = {
    "A30": "no credits/all paid duly", "A31": "all credits at this bank paid duly",
    "A32": "existing credits paid duly", "A33": "delay in paying off in the past",
    "A34": "critical account/other credits existing"
}
purpose_map = {
    "A40": "car (new)", "A41": "car (used)", "A42": "furniture/equipment",
    "A43": "radio/television", "A44": "domestic appliances", "A45": "repairs",
    "A46": "education", "A47": "vacation", "A48": "retraining",
    "A49": "business", "A410": "others"
}
savings_account_map = {
    "A61": "< 100 DM", "A62": "100-500 DM", "A63": "500-1000 DM",
    "A64": ">= 1000 DM", "A65": "unknown/no savings account"
}
employment_since_map = {
    "A71": "unemployed", "A72": "< 1 year", "A73": "1-4 years",
    "A74": "4-7 years", "A75": ">= 7 years"
}
personal_status_sex_map = {
    "A91": "male: divorced/separated", "A92": "female: divorced/separated/married",
    "A93": "male: single", "A94": "male: married/widowed", "A95": "female: single"
}
other_debtors_guarantors_map = {
    "A101": "none", "A102": "co-applicant", "A103": "guarantor"
}
property_map = {
    "A121": "real estate", "A122": "building society/life insurance",
    "A123": "car or other", "A124": "unknown/no property"
}
other_installment_plans_map = {
    "A141": "bank", "A142": "stores", "A143": "none"
}
housing_map = {
    "A151": "rent", "A152": "own", "A153": "for free"
}
job_map = {
    "A171": "unemployed/unskilled non-resident", "A172": "unskilled resident",
    "A173": "skilled employee/official", "A174": "management/highly qualified"
}
telephone_map = {
    "A191": "none", "A192": "yes, registered"
}
foreign_worker_map = {
    "A201": "yes", "A202": "no"
}

In [21]:
df_german["status_checking_account"] = df_german["status_checking_account"].replace(status_checking_account_map)
df_german["credit_history"] = df_german["credit_history"].replace(credit_history_map)
df_german["purpose"] = df_german["purpose"].replace(purpose_map)
df_german["savings_account"] = df_german["savings_account"].replace(savings_account_map)
df_german["employment_since"] = df_german["employment_since"].replace(employment_since_map)
df_german["personal_status_sex"] = df_german["personal_status_sex"].replace(personal_status_sex_map)
df_german["other_debtors_guarantors"] = df_german["other_debtors_guarantors"].replace(other_debtors_guarantors_map)
df_german["property"] = df_german["property"].replace(property_map)
df_german["other_installment_plans"] = df_german["other_installment_plans"].replace(other_installment_plans_map)
df_german["housing"] = df_german["housing"].replace(housing_map)
df_german["job"] = df_german["job"].replace(job_map)
df_german["telephone"] = df_german["telephone"].replace(telephone_map)
df_german["foreign_worker"] = df_german["foreign_worker"].replace(foreign_worker_map)

df_german.head()

,status_checking_account,duration_months,credit_history,purpose,credit_amount,savings_account,employment_since,installment_rate_pct,personal_status_sex,other_debtors_guarantors,...,property,age,other_installment_plans,housing,existing_credits_count,job,num_dependents,telephone,foreign_worker,target
0,< 0 DM,6,critical account/other credits existing,radio/television,1169,unknown/no savings account,>= 7 years,4,male: single,none,...,real estate,67,none,own,2,skilled employee/official,1,"yes, registered",yes,1
1,0 <= ... < 200 DM,48,existing credits paid duly,radio/television,5951,< 100 DM,1-4 years,2,female: divorced/separated/married,none,...,real estate,22,none,own,1,skilled employee/official,1,none,yes,2
2,no checking account,12,critical account/other credits existing,education,2096,< 100 DM,4-7 years,2,male: single,none,...,real estate,49,none,own,1,unskilled resident,2,none,yes,1
3,< 0 DM,42,existing credits paid duly,furniture/equipment,7882,< 100 DM,4-7 years,2,male: single,guarantor,...,building society/life insurance,45,none,for free,1,skilled employee/official,2,none,yes,1
4,< 0 DM,24,delay in paying off in the past,car (new),4870,< 100 DM,1-4 years,3,male: single,none,...,unknown/no property,53,none,for free,2,skilled employee/official,2,none,yes,2

In [22]:
print(df_german["status_checking_account"].unique())
print(df_german["credit_history"].unique())

<StringArray>
[                       '< 0 DM',             '0 <= ... < 200 DM',
           'no checking account', '>= 200 DM / salary assignment']
Length: 4, dtype: str
<StringArray>
['critical account/other credits existing',
              'existing credits paid duly',
         'delay in paying off in the past',
                'no credits/all paid duly',
      'all credits at this bank paid duly']
Length: 5, dtype: str

In [23]:
df_german.isnull().sum()

status_checking_account     0
duration_months             0
credit_history              0
purpose                     0
credit_amount               0
savings_account             0
employment_since            0
installment_rate_pct        0
personal_status_sex         0
other_debtors_guarantors    0
residence_since             0
property                    0
age                         0
other_installment_plans     0
housing                     0
existing_credits_count      0
job                         0
num_dependents              0
telephone                   0
foreign_worker              0
target                      0
dtype: int64

In [24]:
df_german.to_csv(GERMAN_DIR / "german_credit_uci_original.csv", index=False)

In [25]:
# Show column names, data types, and non-null counts for Home Credit
# Useful first check: confirms row/column count and flags which columns
# are numeric vs object (categorical/string) before we look at missingness
df_home.info()

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), str(16)
memory usage: 286.2 MB

In [26]:
# Count missing values per column, sorted from most missing to least
# With 122 columns this output will be long - that's expected for Home Credit
# We'll use this to decide which columns to drop (>20% missing, per our plan)
# and which need imputation
df_home.isnull().sum().sort_values(ascending=False)

COMMONAREA_AVG              214865
COMMONAREA_MODE             214865
COMMONAREA_MEDI             214865
NONLIVINGAPARTMENTS_MEDI    213514
NONLIVINGAPARTMENTS_MODE    213514
                             ...
FLAG_DOCUMENT_16                 0
FLAG_DOCUMENT_15                 0
FLAG_DOCUMENT_14                 0
FLAG_DOCUMENT_20                 0
FLAG_DOCUMENT_21                 0
Length: 122, dtype: int64

In [27]:
# Calculate missingness as a percentage of total rows, not just raw counts
# This lets us directly apply the 20% threshold from our Data Quality Assurance Plan
missing_pct = (df_home.isnull().sum() / len(df_home)) * 100
missing_pct = missing_pct.sort_values(ascending=False)

# Show only columns that actually have any missing values
missing_pct[missing_pct > 0]

COMMONAREA_AVG              69.872297
COMMONAREA_MODE             69.872297
COMMONAREA_MEDI             69.872297
NONLIVINGAPARTMENTS_MEDI    69.432963
NONLIVINGAPARTMENTS_MODE    69.432963
                              ...
EXT_SOURCE_2                 0.214626
AMT_GOODS_PRICE              0.090403
AMT_ANNUITY                  0.003902
CNT_FAM_MEMBERS              0.000650
DAYS_LAST_PHONE_CHANGE       0.000325
Length: 67, dtype: float64

In [28]:
# How many columns exceed 20% missing (candidates to drop, per our plan)
cols_above_threshold = missing_pct[missing_pct > 20]
print(f"Columns above 20% missing: {len(cols_above_threshold)}")
print(cols_above_threshold)

# How many columns have some missingness but are below 20% (candidates for imputation)
cols_below_threshold = missing_pct[(missing_pct > 0) & (missing_pct <= 20)]
print(f"\nColumns with missing values but below 20%: {len(cols_below_threshold)}")
print(cols_below_threshold)

Columns above 20% missing: 50
COMMONAREA_AVG                  69.872297
COMMONAREA_MODE                 69.872297
COMMONAREA_MEDI                 69.872297
NONLIVINGAPARTMENTS_MEDI        69.432963
NONLIVINGAPARTMENTS_MODE        69.432963
NONLIVINGAPARTMENTS_AVG         69.432963
FONDKAPREMONT_MODE              68.386172
LIVINGAPARTMENTS_AVG            68.354953
LIVINGAPARTMENTS_MEDI           68.354953
LIVINGAPARTMENTS_MODE           68.354953
FLOORSMIN_MODE                  67.848630
FLOORSMIN_AVG                   67.848630
FLOORSMIN_MEDI                  67.848630
YEARS_BUILD_AVG                 66.497784
YEARS_BUILD_MODE                66.497784
YEARS_BUILD_MEDI                66.497784
OWN_CAR_AGE                     65.990810
LANDAREA_MEDI                   59.376738
LANDAREA_AVG                    59.376738
LANDAREA_MODE                   59.376738
BASEMENTAREA_MODE               58.515956
BASEMENTAREA_MEDI               58.515956
BASEMENTAREA_AVG                58.515956
EXT_SOURCE_1                    56.381073
NONLIVINGAREA_MODE              55.179164
NONLIVINGAREA_AVG               55.179164
NONLIVINGAREA_MEDI              55.179164
ELEVATORS_AVG                   53.295980
ELEVATORS_MEDI                  53.295980
ELEVATORS_MODE                  53.295980
WALLSMATERIAL_MODE              50.840783
APARTMENTS_AVG                  50.749729
APARTMENTS_MEDI                 50.749729
APARTMENTS_MODE                 50.749729
ENTRANCES_MODE                  50.348768
ENTRANCES_MEDI                  50.348768
ENTRANCES_AVG                   50.348768
LIVINGAREA_AVG                  50.193326
LIVINGAREA_MEDI                 50.193326
LIVINGAREA_MODE                 50.193326
HOUSETYPE_MODE                  50.176091
FLOORSMAX_MODE                  49.760822
FLOORSMAX_AVG                   49.760822
FLOORSMAX_MEDI                  49.760822
YEARS_BEGINEXPLUATATION_MODE    48.781019
YEARS_BEGINEXPLUATATION_MEDI    48.781019
YEARS_BEGINEXPLUATATION_AVG     48.781019
TOTALAREA_MODE                  48.268517
EMERGENCYSTATE_MODE             47.398304
OCCUPATION_TYPE                 31.345545
dtype: float64

Columns with missing values but below 20%: 17
EXT_SOURCE_3                  19.825307
AMT_REQ_CREDIT_BUREAU_HOUR    13.501631
AMT_REQ_CREDIT_BUREAU_WEEK    13.501631
AMT_REQ_CREDIT_BUREAU_MON     13.501631
AMT_REQ_CREDIT_BUREAU_YEAR    13.501631
AMT_REQ_CREDIT_BUREAU_DAY     13.501631
AMT_REQ_CREDIT_BUREAU_QRT     13.501631
NAME_TYPE_SUITE                0.420148
DEF_60_CNT_SOCIAL_CIRCLE       0.332021
OBS_60_CNT_SOCIAL_CIRCLE       0.332021
DEF_30_CNT_SOCIAL_CIRCLE       0.332021
OBS_30_CNT_SOCIAL_CIRCLE       0.332021
EXT_SOURCE_2                   0.214626
AMT_GOODS_PRICE                0.090403
AMT_ANNUITY                    0.003902
CNT_FAM_MEMBERS                0.000650
DAYS_LAST_PHONE_CHANGE         0.000325
dtype: float64

In [29]:
# Check if AMT_REQ_CREDIT_BUREAU_* columns are missing together (same rows)
# If they are, this points to "no bureau inquiry record exists" rather than random gaps
bureau_cols = [
    "AMT_REQ_CREDIT_BUREAU_HOUR", "AMT_REQ_CREDIT_BUREAU_DAY",
    "AMT_REQ_CREDIT_BUREAU_WEEK", "AMT_REQ_CREDIT_BUREAU_MON",
    "AMT_REQ_CREDIT_BUREAU_QRT", "AMT_REQ_CREDIT_BUREAU_YEAR"
]

# True if a row is missing across ALL of these columns at once
same_rows_missing = df_home[bureau_cols].isnull().all(axis=1).sum()
print(f"Rows missing across ALL bureau columns simultaneously: {same_rows_missing}")
print(f"Rows missing in at least one bureau column: {df_home[bureau_cols].isnull().any(axis=1).sum()}")

Rows missing across ALL bureau columns simultaneously: 41519
Rows missing in at least one bureau column: 41519

In [30]:
# Check if OWN_CAR_AGE is missing specifically for applicants who don't own a car
# FLAG_OWN_CAR should be 'N' for anyone missing OWN_CAR_AGE, if our theory is right
pd.crosstab(df_home["OWN_CAR_AGE"].isnull(), df_home["FLAG_OWN_CAR"])

FLAG_OWN_CAR       N       Y
OWN_CAR_AGE
False              0  104582
True          202924       5

In [31]:
# Check whether OCCUPATION_TYPE missingness lines up with NAME_INCOME_TYPE
# (e.g. pensioners/unemployed people would have no occupation to report)
pd.crosstab(df_home["OCCUPATION_TYPE"].isnull(), df_home["NAME_INCOME_TYPE"])

NAME_INCOME_TYPE,Businessman,Commercial associate,Maternity leave,Pensioner,State servant,Student,Unemployed,Working
OCCUPATION_TYPE,,,,,,,,
False,8,59320,4,5,17916,13,0,133854
True,2,12297,1,55357,3787,5,22,24920

In [32]:
# Columns to drop: >20% missing, structural/property attributes
# OWN_CAR_AGE is deliberately excluded despite being >20% missing -
# we've confirmed its missingness is explained by FLAG_OWN_CAR == 'N' (MAR),
# so it's handled separately below rather than dropped
cols_to_drop = missing_pct[missing_pct > 20].index.tolist()
cols_to_drop.remove("OWN_CAR_AGE")

print(f"Dropping {len(cols_to_drop)} columns above 20% missing (OWN_CAR_AGE kept deliberately)")
df_home = df_home.drop(columns=cols_to_drop)
print(f"New shape: {df_home.shape}")

Dropping 49 columns above 20% missing (OWN_CAR_AGE kept deliberately)
New shape: (307511, 73)

In [33]:
# For non-car-owners, missing OWN_CAR_AGE means "not applicable" -> impute 0
df_home.loc[df_home["FLAG_OWN_CAR"] == "N", "OWN_CAR_AGE"] = 0

# For the small number of car owners still missing OWN_CAR_AGE (genuine gaps),
# impute using the median age among actual car owners only
car_owner_median_age = df_home.loc[df_home["FLAG_OWN_CAR"] == "Y", "OWN_CAR_AGE"].median()
df_home.loc[
    (df_home["FLAG_OWN_CAR"] == "Y") & (df_home["OWN_CAR_AGE"].isnull()),
    "OWN_CAR_AGE"
] = car_owner_median_age

# Confirm no missing values remain
print(df_home["OWN_CAR_AGE"].isnull().sum())

0

In [34]:
# OCCUPATION_TYPE was dropped in Cell 7 - reload just that column from the
# original raw file and reattach it to df_home using the shared index,
# since row order has not changed
df_home_original = pd.read_csv(
    DATA_DIR / "Home Credit Default Risk Dataset" / "application_train.csv",
    usecols=["SK_ID_CURR", "OCCUPATION_TYPE"]
)

# Merge back on SK_ID_CURR (safer than relying on row index/order matching)
df_home = df_home.merge(df_home_original, on="SK_ID_CURR", how="left")

print(df_home.shape)  # should now show 74 columns (73 + OCCUPATION_TYPE back)
print(df_home["OCCUPATION_TYPE"].isnull().sum())  # should show ~96,391 missing

(307511, 74)
96391

In [35]:
# Rather than dropping OCCUPATION_TYPE, treat "no occupation recorded" as its
# own meaningful category rather than losing a variable likely relevant to
# credit risk (occupation relates to income stability)
df_home["OCCUPATION_TYPE"] = df_home["OCCUPATION_TYPE"].fillna("Unknown/Not Applicable")

# Confirm no missing values remain, and check the new category's size
print(df_home["OCCUPATION_TYPE"].isnull().sum())
print(df_home["OCCUPATION_TYPE"].value_counts())

0
OCCUPATION_TYPE
Unknown/Not Applicable    96391
Laborers                  55186
Sales staff               32102
Core staff                27570
Managers                  21371
Drivers                   18603
High skill tech staff     11380
Accountants                9813
Medicine staff             8537
Security staff             6721
Cooking staff              5946
Cleaning staff             4653
Private service staff      2652
Low-skill Laborers         2093
Waiters/barmen staff       1348
Secretaries                1305
Realty agents               751
HR staff                    563
IT staff                    526
Name: count, dtype: int64

In [36]:
# AMT_REQ_CREDIT_BUREAU_* columns (13.5% missing, confirmed missing together
# in Cell 5 - representing "no bureau inquiry history"). Impute 0, since
# absence of a recorded inquiry count most plausibly means zero inquiries
bureau_cols = [
    "AMT_REQ_CREDIT_BUREAU_HOUR", "AMT_REQ_CREDIT_BUREAU_DAY",
    "AMT_REQ_CREDIT_BUREAU_WEEK", "AMT_REQ_CREDIT_BUREAU_MON",
    "AMT_REQ_CREDIT_BUREAU_QRT", "AMT_REQ_CREDIT_BUREAU_YEAR"
]
df_home[bureau_cols] = df_home[bureau_cols].fillna(0)

print(df_home[bureau_cols].isnull().sum())

AMT_REQ_CREDIT_BUREAU_HOUR    0
AMT_REQ_CREDIT_BUREAU_DAY     0
AMT_REQ_CREDIT_BUREAU_WEEK    0
AMT_REQ_CREDIT_BUREAU_MON     0
AMT_REQ_CREDIT_BUREAU_QRT     0
AMT_REQ_CREDIT_BUREAU_YEAR    0
dtype: int64

In [37]:
# EXT_SOURCE_2 (0.2% missing) and EXT_SOURCE_3 (19.8% missing) are external
# normalized credit scores - no clear structural "not applicable" logic here,
# so apply standard median imputation per our Data Quality Assurance Plan
df_home["EXT_SOURCE_2"] = df_home["EXT_SOURCE_2"].fillna(df_home["EXT_SOURCE_2"].median())
df_home["EXT_SOURCE_3"] = df_home["EXT_SOURCE_3"].fillna(df_home["EXT_SOURCE_3"].median())

print(df_home[["EXT_SOURCE_2", "EXT_SOURCE_3"]].isnull().sum())

EXT_SOURCE_2    0
EXT_SOURCE_3    0
dtype: int64

In [38]:
# Handle the last handful of near-zero missingness columns:
# numeric columns -> median, categorical columns -> mode
remaining_missing = df_home.columns[df_home.isnull().sum() > 0]
print("Columns still with missing values:", remaining_missing.tolist())

for col in remaining_missing:
    if df_home[col].dtype in ["float64", "int64"]:
        df_home[col] = df_home[col].fillna(df_home[col].median())
    else:
        df_home[col] = df_home[col].fillna(df_home[col].mode()[0])

# Final confirmation - should be zero everywhere now
print(df_home.isnull().sum().sum())

Columns still with missing values: ['AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'CNT_FAM_MEMBERS', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE']
0

In [39]:
# Save the cleaned Home Credit dataset locally
HOME_DIR = DATA_DIR / "Home Credit Default Risk Dataset"
df_home.to_csv(HOME_DIR / "application_train_cleaned.csv", index=False)
print("Saved:", df_home.shape)

Saved: (307511, 74)

In [40]:
# Inspect LendingClub structure - dtypes, non-null counts
df_lending.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 56 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        10000 non-null  int64
 1   emp_title                         9167 non-null   str
 2   emp_length                        9183 non-null   float64
 3   state                             10000 non-null  str
 4   homeownership                     10000 non-null  str
 5   annual_income                     10000 non-null  float64
 6   verified_income                   10000 non-null  str
 7   debt_to_income                    9976 non-null   float64
 8   annual_income_joint               1495 non-null   float64
 9   verification_income_joint         1455 non-null   str
 10  debt_to_income_joint              1495 non-null   float64
 11  delinq_2y                         10000 non-null  int64
 12  months_since_last_delinq          4342 non-null   float64
 13  earliest_credit_line              10000 non-null  int64
 14  inquiries_last_12m                10000 non-null  int64
 15  total_credit_lines                10000 non-null  int64
 16  open_credit_lines                 10000 non-null  int64
 17  total_credit_limit                10000 non-null  int64
 18  total_credit_utilized             10000 non-null  int64
 19  num_collections_last_12m          10000 non-null  int64
 20  num_historical_failed_to_pay      10000 non-null  int64
 21  months_since_90d_late             2285 non-null   float64
 22  current_accounts_delinq           10000 non-null  int64
 23  total_collection_amount_ever      10000 non-null  int64
 24  current_installment_accounts      10000 non-null  int64
 25  accounts_opened_24m               10000 non-null  int64
 26  months_since_last_credit_inquiry  8729 non-null   float64
 27  num_satisfactory_accounts         10000 non-null  int64
 28  num_accounts_120d_past_due        9682 non-null   float64
 29  num_accounts_30d_past_due         10000 non-null  int64
 30  num_active_debit_accounts         10000 non-null  int64
 31  total_debit_limit                 10000 non-null  int64
 32  num_total_cc_accounts             10000 non-null  int64
 33  num_open_cc_accounts              10000 non-null  int64
 34  num_cc_carrying_balance           10000 non-null  int64
 35  num_mort_accounts                 10000 non-null  int64
 36  account_never_delinq_percent      10000 non-null  float64
 37  tax_liens                         10000 non-null  int64
 38  public_record_bankrupt            10000 non-null  int64
 39  loan_purpose                      10000 non-null  str
 40  application_type                  10000 non-null  str
 41  loan_amount                       10000 non-null  int64
 42  term                              10000 non-null  int64
 43  interest_rate                     10000 non-null  float64
 44  installment                       10000 non-null  float64
 45  grade                             10000 non-null  str
 46  sub_grade                         10000 non-null  str
 47  issue_month                       10000 non-null  str
 48  loan_status                       10000 non-null  str
 49  initial_listing_status            10000 non-null  str
 50  disbursement_method               10000 non-null  str
 51  balance                           10000 non-null  float64
 52  paid_total                        10000 non-null  float64
 53  paid_principal                    10000 non-null  float64
 54  paid_interest                     10000 non-null  float64
 55  paid_late_fees                    10000 non-null  float64
dtypes: float64(17), int64(26), str(13)
memory usage: 4.3 MB

In [41]:
# Calculate missingness as a percentage, same approach as Home Credit
missing_pct_lending = (df_lending.isnull().sum() / len(df_lending)) * 100
missing_pct_lending = missing_pct_lending.sort_values(ascending=False)
missing_pct_lending[missing_pct_lending > 0]

verification_income_joint           85.45
annual_income_joint                 85.05
debt_to_income_joint                85.05
months_since_90d_late               77.15
months_since_last_delinq            56.58
months_since_last_credit_inquiry    12.71
emp_title                            8.33
emp_length                           8.17
num_accounts_120d_past_due           3.18
debt_to_income                       0.24
dtype: float64

In [42]:
# Check whether missing joint-income fields correspond to Individual applications
# (where joint fields simply wouldn't apply)
pd.crosstab(df_lending["annual_income_joint"].isnull(), df_lending["application_type"])

application_type     individual  joint
annual_income_joint
False                         0   1495
True                       8505      0

In [43]:
# If delinq_2y (count of delinquencies in last 2 years) is 0 for most rows
# where months_since_last_delinq is missing, that supports "never happened"
# rather than "data unavailable"
pd.crosstab(df_lending["months_since_last_delinq"].isnull(), df_lending["delinq_2y"] == 0)

delinq_2y                 False  True
months_since_last_delinq
False                      1412   2930
True                         12   5646

In [44]:
# Joint-income fields are missing exactly when application_type is "individual" -
# confirmed 100% clean structural MAR. Impute 0 for numeric, "Not Applicable" for categorical,
# since these applicants simply have no joint co-borrower
df_lending["annual_income_joint"] = df_lending["annual_income_joint"].fillna(0)
df_lending["debt_to_income_joint"] = df_lending["debt_to_income_joint"].fillna(0)
df_lending["verification_income_joint"] = df_lending["verification_income_joint"].fillna("Not Applicable")

print(df_lending[["annual_income_joint", "debt_to_income_joint", "verification_income_joint"]].isnull().sum())

annual_income_joint          0
debt_to_income_joint         0
verification_income_joint    0
dtype: int64

In [45]:
# Missing months_since_last_delinq is confirmed to correspond overwhelmingly (99.8%)
# with delinq_2y == 0, i.e. no delinquency has ever occurred - not a real data gap.
# Impute with a large sentinel value (999) to represent "no delinquency on record",
# which keeps the column numeric and lets models learn this is functionally "very long ago / never"
df_lending["months_since_last_delinq"] = df_lending["months_since_last_delinq"].fillna(999)
df_lending["months_since_90d_late"] = df_lending["months_since_90d_late"].fillna(999)
df_lending["months_since_last_credit_inquiry"] = df_lending["months_since_last_credit_inquiry"].fillna(999)

print(df_lending[["months_since_last_delinq", "months_since_90d_late", "months_since_last_credit_inquiry"]].isnull().sum())

months_since_last_delinq            0
months_since_90d_late               0
months_since_last_credit_inquiry    0
dtype: int64

In [46]:
# emp_title/emp_length: likely unemployed or non-disclosed - treat as its own category/value
df_lending["emp_title"] = df_lending["emp_title"].fillna("Not Disclosed")
df_lending["emp_length"] = df_lending["emp_length"].fillna(0)  # 0 years = plausible for unemployed/new

# Remaining numeric gaps: standard median imputation per our plan
df_lending["num_accounts_120d_past_due"] = df_lending["num_accounts_120d_past_due"].fillna(
    df_lending["num_accounts_120d_past_due"].median())
df_lending["debt_to_income"] = df_lending["debt_to_income"].fillna(df_lending["debt_to_income"].median())

# Final check - should be zero
print(df_lending.isnull().sum().sum())

0

In [47]:
# Save the cleaned LendingClub dataset locally
LENDING_DIR = DATA_DIR / "Lending Club Loan Dataset"
df_lending.to_csv(LENDING_DIR / "loans_full_schema_cleaned.csv", index=False)
print("Saved:", df_lending.shape)

Saved: (10000, 56)